
import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Providers } from "./features/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// app/layout.tsx
// "use client";  // This makes it a Client Component

// import { Provider } from 'react-redux';
// import store from './store';  // Adjust your store import as needed
// import "./globals.css";  // Your global CSS

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <Provider store={store}>
//       {children}
//     </Provider>
//   );
// }
